export const facultyCoordinators = [
  {
    name: "Dr. Ananya Kulkarni",
    photo: "https://i.pravatar.cc/400?img=47",
    designation: "Associate Professor",
    department: "Computer Engineering",
    email: "ananya.kulkarni@nmiet.edu.in",
    phone: "+91 98765 43210",
    role: "Faculty SPOC",
  },
  {
    name: "Prof. Rahul Deshmukh",
    photo: "https://i.pravatar.cc/400?img=12",
    designation: "Assistant Professor",
    department: "Information Technology",
    email: "rahul.deshmukh@nmiet.edu.in",
    phone: "+91 98765 43211",
    role: "Faculty Coordinator",
  },
  {
    name: "Dr. Meera Joshi",
    photo: "https://i.pravatar.cc/400?img=45",
    designation: "Professor",
    department: "Electronics & Telecommunication",
    email: "meera.joshi@nmiet.edu.in",
    role: "Innovation Cell Head",
  },
  {
    name: "Prof. Kunal Shah",
    photo: "https://i.pravatar.cc/400?img=11",
    designation: "Assistant Professor",
    department: "Artificial Intelligence & Data Science",
    email: "kunal.shah@nmiet.edu.in",
    role: "Department Coordinator",
  },
];

export const studentCommittee = [
  {
    name: "Aarav Patil",
    photo: "https://i.pravatar.cc/300?img=13",
    year: "Final Year",
    department: "Computer Engineering",
    role: "Student SPOC",
  },
  {
    name: "Isha Mehta",
    photo: "https://i.pravatar.cc/300?img=44",
    year: "Third Year",
    department: "Information Technology",
    role: "Technical Lead",
  },
  {
    name: "Vedant Kulkarni",
    photo: "https://i.pravatar.cc/300?img=14",
    year: "Final Year",
    department: "Computer Engineering",
    role: "Operations",
  },
  {
    name: "Riya Sharma",
    photo: "https://i.pravatar.cc/300?img=49",
    year: "Third Year",
    department: "AI & Data Science",
    role: "Design Lead",
  },
  {
    name: "Arjun Nair",
    photo: "https://i.pravatar.cc/300?img=15",
    year: "Second Year",
    department: "Electronics & Telecommunication",
    role: "Media Team",
  },
  {
    name: "Sneha Jadhav",
    photo: "https://i.pravatar.cc/300?img=46",
    year: "Third Year",
    department: "Information Technology",
    role: "Registration Team",
  },
  {
    name: "Kabir Singh",
    photo: "https://i.pravatar.cc/300?img=16",
    year: "Second Year",
    department: "Computer Engineering",
    role: "Volunteer Coordinator",
  },
  {
    name: "Tanvi Rao",
    photo: "https://i.pravatar.cc/300?img=48",
    year: "Third Year",
    department: "AI & Data Science",
    role: "Documentation",
  },
];

export const responsibilities = [
  "Student Registrations",
  "Internal Evaluation",
  "Faculty Coordination",
  "Technical Support",
  "Communication",
  "Documentation",
  "Result Announcement",
  "Mentorship",
];
