import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { FileUp, ShieldCheck, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { pptApi, type PptSession } from "@/lib/ppt-api";

export const Route = createFileRoute("/ppt-submission")({ component: PptSubmission });
function PptSubmission(){
 const [reference,setReference]=useState(""),[email,setEmail]=useState(""),[session,setSession]=useState<PptSession|null>(null),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[done,setDone]=useState<{version:number;uploaded_at:string}|null>(null);
 const verify=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{setSession(await pptApi.verify(reference,email));toast.success("Registration verified");}catch(x){toast.error((x as Error).message)}finally{setBusy(false)}};
 const upload=async(e:React.FormEvent)=>{e.preventDefault();if(!session||!file)return;if(file.size>25*1024*1024)return toast.error("File must be 25 MB or smaller.");if(!/\.(ppt|pptx|pdf)$/i.test(file.name))return toast.error("Upload a .ppt, .pptx or .pdf file.");setBusy(true);try{const result=await pptApi.upload(file,session.token);setDone(result);toast.success("PPT submitted successfully");}catch(x){toast.error((x as Error).message)}finally{setBusy(false)}};
 return <div className="mesh-bg min-h-dvh pt-28 pb-16"><section className="shell max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Secure submission</p><h1 className="mt-2 font-display text-4xl font-bold">Upload your SIH PPT</h1><p className="mt-3 text-muted-foreground">Verify your registration, then submit your presentation. Re-uploads are recorded as a new version until the published deadline.</p>{done?<div className="mt-8 rounded-3xl border bg-card p-8 shadow-lift"><CheckCircle2 className="text-emerald-600" size={42}/><h2 className="mt-4 text-2xl font-bold">Version {done.version} received</h2><p className="mt-2 text-muted-foreground">Uploaded {new Date(done.uploaded_at).toLocaleString()}. A confirmation has been sent to the team leader.</p><Button className="mt-6" onClick={()=>{setDone(null);setFile(null)}}>Upload another version</Button></div>:!session?<form onSubmit={verify} className="mt-8 rounded-3xl border bg-card p-6 shadow-lift"><div className="flex items-center gap-3"><ShieldCheck className="text-primary"/><h2 className="font-display text-xl font-bold">Verify your team</h2></div><Input className="mt-5" placeholder="Reference ID (e.g. SIH2026-0001)" value={reference} onChange={e=>setReference(e.target.value)} required/><Input className="mt-3" type="email" placeholder="Leader email" value={email} onChange={e=>setEmail(e.target.value)} required/><Button className="mt-5" disabled={busy}>{busy?"Verifying…":"Verify registration"}</Button></form>:<form onSubmit={upload} className="mt-8 rounded-3xl border bg-card p-6 shadow-lift"><div className="rounded-2xl bg-muted p-4 text-sm"><b>{session.team_name}</b><span className="block mt-1 text-muted-foreground">{session.reference_id} · {session.ps_id} · {session.theme}</span></div><label className="mt-5 flex cursor-pointer flex-col items-center rounded-2xl border border-dashed p-8 text-center hover:bg-accent"><FileUp className="text-primary"/><span className="mt-3 font-semibold">{file?file.name:"Choose PPT or PDF"}</span><span className="mt-1 text-xs text-muted-foreground">.ppt, .pptx or .pdf · maximum 25 MB</span><input className="sr-only" type="file" accept=".ppt,.pptx,.pdf,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label><div className="mt-5 flex gap-3"><Button disabled={!file||busy}>{busy?"Uploading securely…":"Submit PPT"}</Button><Button type="button" variant="outline" onClick={()=>setSession(null)}>Use another team</Button></div></form>}<p className="mt-6 text-sm text-muted-foreground">Need help? Read the <Link className="font-semibold text-primary" to="/submission-guidelines">submission guidelines</Link> or download the <Link className="font-semibold text-primary" to="/ppt-template">official template</Link>.</p></section></div>
}
