import { createFileRoute, redirect } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { AdminPage } from "@/components/admin-panel";
import { adminApi } from "@/lib/admin-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

export const Route = createFileRoute("/admin/users")({ component: UsersPage });
function UsersPage(){const me=useQuery({queryKey:["admin","me"],queryFn:adminApi.me,retry:false});if(me.data&&me.data.role!=="super_admin")throw redirect({to:"/admin/dashboard"});return <AdminPage page="dashboard"><Users/></AdminPage>}
function Users(){const client=useQueryClient(),[search,setSearch]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[role,setRole]=useState("faculty");const q=useQuery({queryKey:["admin","users",search],queryFn:()=>adminApi.users(search)});const create=useMutation({mutationFn:()=>adminApi.createUser({name,email,password,role,is_active:true}),onSuccess:()=>{setName("");setEmail("");setPassword("");client.invalidateQueries({queryKey:["admin","users"]});toast.success("Admin created")},onError:(e:Error)=>toast.error(e.message)});const remove=useMutation({mutationFn:adminApi.deleteUser,onSuccess:()=>client.invalidateQueries({queryKey:["admin","users"]})});return <><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Access control</p><h1 className="mt-1 text-3xl font-bold">Admin users</h1></div><section className="rounded-2xl border bg-card p-5 shadow-soft"><div className="grid gap-3 md:grid-cols-4"><Input placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><Input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><Input type="password" placeholder="Temporary password" value={password} onChange={e=>setPassword(e.target.value)}/><select className="rounded-xl border bg-background px-3" value={role} onChange={e=>setRole(e.target.value)}>{["super_admin","faculty","student_spoc","student_coordinator"].map(r=><option key={r}>{r}</option>)}</select></div><Button className="mt-3" disabled={!name||!email||password.length<8||create.isPending} onClick={()=>create.mutate()}>Create admin</Button></section><Input className="my-5 max-w-md" placeholder="Search name, email or role" value={search} onChange={e=>setSearch(e.target.value)}/><section className="overflow-x-auto rounded-2xl border bg-card shadow-soft"><table className="w-full min-w-[700px] text-sm"><thead className="bg-muted text-left text-xs uppercase text-muted-foreground"><tr>{["Name","Email","Role","Status","Actions"].map(x=><th className="px-5 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{q.data?.data.map(u=><tr className="border-t" key={u._id}><td className="px-5 py-4 font-semibold">{u.name}</td><td className="px-5 py-4">{u.email}</td><td className="px-5 py-4 capitalize">{u.role.replace("_"," ")}</td><td className="px-5 py-4">{u.is_active?"Active":"Disabled"}</td><td className="px-5 py-4"><button className="font-semibold text-destructive" onClick={()=>remove.mutate(u._id)}>Delete</button></td></tr>)}</tbody></table></section></>}
