import { Link, useNavigate } from "@tanstack/react-router";
import { BarChart3, Bell, ClipboardList, FileText, LayoutDashboard, LogOut, Mail, Menu, Search, ShieldCheck, Users, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { adminApi, type AdminRegistration, type AdminUser } from "@/lib/admin-api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const links = [{ to: "/admin/dashboard", label: "Overview", icon: LayoutDashboard }, { to: "/admin/registrations", label: "Registrations", icon: Users }, { to: "/admin/ppt", label: "PPT submissions", icon: FileText }, { to: "/admin/announcements", label: "Announcements", icon: Bell }, { to: "/admin/email", label: "Email centre", icon: Mail }, { to: "/admin/activity", label: "Activity log", icon: ClipboardList }];
const statuses = ["Registered", "PPT Submitted", "Under Review", "Shortlisted", "Rejected", "Qualified"];

export function AdminLogin() {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { adminApi.me().then(() => navigate({ to: "/admin/dashboard" })).catch(() => undefined); }, [navigate]);
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); try { await adminApi.login(email, password); navigate({ to: "/admin/dashboard" }); } catch (err) { toast.error(err instanceof Error ? err.message : "Unable to sign in"); } finally { setLoading(false); } }
  return <main className="mesh-bg flex min-h-dvh items-center justify-center px-4 py-10"><section className="w-full max-w-md rounded-3xl border border-border bg-card p-8 shadow-lift"><div className="mb-8 flex size-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><ShieldCheck /></div><p className="text-sm font-semibold uppercase tracking-[.18em] text-primary">NMIET SIH 2026</p><h1 className="mt-2 text-3xl font-bold">Organizer sign in</h1><p className="mt-2 text-sm text-muted-foreground">Use your assigned organizer account to access the internal selection workspace.</p><form className="mt-7 space-y-4" onSubmit={submit}><label className="block text-sm font-medium">Email<Input className="mt-1.5" type="email" value={email} onChange={e => setEmail(e.target.value)} required autoComplete="email" /></label><label className="block text-sm font-medium">Password<Input className="mt-1.5" type="password" value={password} onChange={e => setPassword(e.target.value)} required minLength={8} autoComplete="current-password" /></label><Button className="w-full" disabled={loading}>{loading ? "Signing in…" : "Sign in securely"}</Button></form><Link to="/" className="mt-6 block text-center text-sm text-muted-foreground hover:text-foreground">← Return to portal</Link></section></main>;
}

export function AdminPage({ page }: { page: "dashboard" | "registrations" | "ppt" | "announcements" | "email" | "activity" }) {
  const navigate = useNavigate(); const [user, setUser] = useState<AdminUser | null>(null); const [open, setOpen] = useState(false);
  useEffect(() => { adminApi.me().then(setUser).catch(() => navigate({ to: "/admin/login", replace: true })); }, [navigate]);
  if (!user) return <main className="flex min-h-dvh items-center justify-center text-sm text-muted-foreground">Verifying secure session…</main>;
  return <div className="min-h-dvh bg-background"><aside className={`${open ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-border bg-card p-5 transition-transform lg:translate-x-0`}><div className="flex items-center gap-3 px-2"><div className="flex size-10 items-center justify-center rounded-xl bg-primary text-primary-foreground"><ShieldCheck size={20}/></div><div><p className="font-display font-bold">NMIET SIH</p><p className="text-xs text-muted-foreground">Admin workspace</p></div><button className="ml-auto lg:hidden" onClick={() => setOpen(false)}><X size={18}/></button></div><nav className="mt-9 space-y-1">{links.map(({to,label,icon: Icon}) => <Link key={to} to={to} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition-colors ${page === to.split("/").pop() || (page === "dashboard" && to.endsWith("dashboard")) ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-accent hover:text-foreground"}`}><Icon size={18}/>{label}</Link>)}</nav><div className="mt-auto rounded-2xl bg-muted p-3"><p className="truncate text-sm font-semibold">{user.name}</p><p className="mt-0.5 text-xs capitalize text-muted-foreground">{user.role.replace("_", " ")}</p><button onClick={async () => { await adminApi.logout(); navigate({ to: "/admin/login" }); }} className="mt-3 flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-destructive"><LogOut size={14}/> Sign out</button></div></aside><main className="lg:pl-72"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-border bg-background/90 px-5 backdrop-blur lg:px-9"><button className="mr-3 lg:hidden" onClick={() => setOpen(true)}><Menu/></button><div className="ml-auto flex items-center gap-3"><Bell size={18} className="text-muted-foreground"/><span className="hidden text-sm text-muted-foreground sm:block">Internal only</span></div></header><div className="mx-auto max-w-7xl p-5 lg:p-9">{page === "dashboard" && <Dashboard/>}{page === "registrations" && <Registrations/>}{page === "ppt" && <Ppt/>}{page === "announcements" && <Announcements/>}{page === "email" && <Email/>}{page === "activity" && <Activity/>}</div></main></div>;
}

function Title({ kicker, title, children }: { kicker: string; title: string; children?: React.ReactNode }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{kicker}</p><h1 className="mt-1 text-3xl font-bold">{title}</h1></div>{children}</div>; }
function Status({ value = "Registered" }: { value?: string }) { const styles: Record<string,string> = { "Qualified": "bg-emerald-500/15 text-emerald-700", "Shortlisted": "bg-blue-500/15 text-blue-700", "Rejected": "bg-red-500/15 text-red-700", "Under Review": "bg-amber-500/15 text-amber-700", "PPT Submitted": "bg-violet-500/15 text-violet-700" }; return <Badge className={`border-0 ${styles[value] || "bg-muted text-muted-foreground"}`}>{value}</Badge>; }
function Dashboard() { const [data, setData] = useState<{ metrics: Record<string,number>; latest: AdminRegistration[] }>(); useEffect(() => { adminApi.dashboard().then(setData).catch(e => toast.error(e.message)); }, []); const cards = [["Total registrations", "total"], ["Software teams", "software"], ["Hardware teams", "hardware"], ["PPT submitted", "ppt_submitted"], ["Shortlisted", "shortlisted"], ["Qualified", "qualified"]]; return <><Title kicker="Command centre" title="Selection overview"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([label,key]) => <div key={key} className="rounded-2xl border border-border bg-card p-5 shadow-soft"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{data?.metrics[key] ?? "—"}</p></div>)}</div><section className="mt-8 rounded-2xl border border-border bg-card shadow-soft"><div className="flex items-center justify-between border-b border-border p-5"><h2 className="font-display text-lg font-bold">Latest registrations</h2><Link to="/admin/registrations" className="text-sm font-semibold text-primary">View all</Link></div><RegistrationTable rows={data?.latest ?? []}/></section></>; }
function Registrations() { const [rows,setRows]=useState<AdminRegistration[]>([]), [search,setSearch]=useState(""), [status,setStatus]=useState(""); const load=()=>adminApi.registrations(`?${new URLSearchParams({ ...(search ? {search} : {}), ...(status ? {status} : {}) })}`).then(r=>setRows(r.data)).catch(e=>toast.error(e.message)); useEffect(load, []); return <><Title kicker="Team management" title="Registrations"><Button onClick={load}><Search size={16}/> Refresh results</Button></Title><div className="mb-4 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><Input placeholder="Search team, leader or PS ID" value={search} onChange={e=>setSearch(e.target.value)}/><select className="rounded-xl border border-input bg-background px-3 text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><Button onClick={load}>Apply filters</Button></div><section className="overflow-hidden rounded-2xl border border-border bg-card shadow-soft"><RegistrationTable rows={rows} editable onChanged={load}/></section></>; }
function RegistrationTable({rows,editable,onChanged}:{rows:AdminRegistration[]; editable?:boolean; onChanged?:()=>void}) { return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-muted/70 text-xs uppercase tracking-wide text-muted-foreground"><tr>{["Team", "Leader", "PS ID", "Theme", "Category", "Status", "Registered", "Actions"].map(x=><th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row._id} className="border-t border-border"><td className="px-5 py-4 font-semibold">{row.team?.teamName || "Untitled"}</td><td className="px-5 py-4">{row.leader?.name || "—"}</td><td className="px-5 py-4">{row.team?.psId || "—"}</td><td className="px-5 py-4">{row.team?.theme || "—"}</td><td className="px-5 py-4">{row.team?.category || "—"}</td><td className="px-5 py-4"><Status value={row.status}/></td><td className="px-5 py-4 text-muted-foreground">{row.created_at ? new Date(row.created_at).toLocaleDateString() : "—"}</td><td className="px-5 py-4">{editable ? <div className="flex gap-2"><select aria-label="Change status" className="max-w-32 rounded-lg border border-input bg-background px-2 py-1 text-xs" defaultValue={row.status || "Registered"} onChange={async e=>{try{await adminApi.updateRegistration(row._id,{status:e.target.value}); toast.success("Status updated");onChanged?.()}catch(err){toast.error(err instanceof Error?err.message:"Update failed")}}}>{statuses.map(x=><option key={x}>{x}</option>)}</select><button className="text-xs font-semibold text-destructive" onClick={async()=>{if(confirm(`Soft-delete ${row.team?.teamName || "this registration"}?`)){try{await adminApi.deleteRegistration(row._id);toast.success("Registration moved to archive");onChanged?.()}catch(e){toast.error(e instanceof Error?e.message:"Delete failed")}}}}>Delete</button></div> : "—"}</td></tr>)}{!rows.length&&<tr><td colSpan={8} className="px-5 py-12 text-center text-muted-foreground">No registrations found.</td></tr>}</tbody></table></div>; }
function Ppt(){const [rows,setRows]=useState<AdminRegistration[]>([]);useEffect(()=>{adminApi.registrations().then(r=>setRows(r.data.filter(x=>x.pptUrl||x.status==="PPT Submitted")))},[]);return <><Title kicker="Review workspace" title="PPT submissions"/><section className="rounded-2xl border border-border bg-card shadow-soft"><RegistrationTable rows={rows}/></section></>}
function Announcements(){const [items,setItems]=useState<any[]>([]),[title,setTitle]=useState(""),[body,setBody]=useState("");const load=()=>adminApi.announcements().then(x=>setItems(x.data));useEffect(load,[]);return <><Title kicker="Portal updates" title="Announcements"/><section className="rounded-2xl border border-border bg-card p-6 shadow-soft"><div className="grid gap-3"><Input placeholder="Announcement title" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="min-h-28 rounded-xl border border-input bg-background p-3 text-sm" placeholder="Write an internal or public announcement" value={body} onChange={e=>setBody(e.target.value)}/><Button className="w-fit" onClick={async()=>{try{await adminApi.createAnnouncement({title,body,is_pinned:false});setTitle("");setBody("");load();toast.success("Announcement created")}catch(e){toast.error(e instanceof Error?e.message:"Could not create announcement")}}}>Publish announcement</Button></div><div className="mt-7 divide-y divide-border">{items.map(item=><div key={item._id} className="flex gap-4 py-4"><div className="min-w-0 flex-1"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-muted-foreground">{item.body}</p></div><button className="h-fit text-sm font-semibold text-destructive" onClick={async()=>{await adminApi.deleteAnnouncement(item._id);load()}}>Delete</button></div>)}</div></section></>}
function Email(){const [recipient,setRecipient]=useState("All Teams"),[body,setBody]=useState("Dear {{team_name}},\n\n");return <><Title kicker="Communications" title="Email centre"/><section className="max-w-3xl rounded-2xl border border-border bg-card p-6 shadow-soft"><p className="text-sm text-muted-foreground">Compose an announcement for a filtered group. Variables are resolved only by the delivery service.</p><label className="mt-5 block text-sm font-semibold">Recipients<select className="mt-2 w-full rounded-xl border border-input bg-background p-3" value={recipient} onChange={e=>setRecipient(e.target.value)}>{["All Teams","Selected Teams","Theme","Category","Status","Individual Team"].map(x=><option key={x}>{x}</option>)}</select></label><label className="mt-4 block text-sm font-semibold">Message<textarea className="mt-2 min-h-48 w-full rounded-xl border border-input bg-background p-3 font-sans text-sm" value={body} onChange={e=>setBody(e.target.value)}/></label><div className="mt-4 flex flex-wrap gap-2 text-xs text-muted-foreground"><span>Available:</span>{["{{team_name}}","{{leader_name}}","{{ps_id}}","{{theme}}"].map(x=><code key={x} className="rounded bg-muted px-2 py-1">{x}</code>)}</div><Button className="mt-6" onClick={()=>toast.info("Email delivery needs an approved transactional-email provider before messages can be sent.")}>Send for approval</Button></section></>}
function Activity(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{adminApi.activity().then(x=>setItems(x.data))},[]);return <><Title kicker="Accountability" title="Activity log"/><section className="divide-y divide-border rounded-2xl border border-border bg-card shadow-soft">{items.map(item=><div key={item._id} className="p-5"><p className="font-semibold">{item.admin_name} <span className="font-normal text-muted-foreground">{item.action}</span></p>{item.detail&&<p className="mt-1 text-sm text-muted-foreground">{item.detail}</p>}<p className="mt-2 text-xs text-muted-foreground">{new Date(item.timestamp).toLocaleString()}</p></div>)}{!items.length&&<p className="p-10 text-center text-sm text-muted-foreground">No recorded activity yet.</p>}</section></>}
