from dotenv import load_dotenv
import os

load_dotenv()

MONGODB_URI = os.getenv("MONGODB_URI")
DATABASE_NAME = os.getenv("DATABASE_NAME")
ADMIN_JWT_SECRET = os.getenv("ADMIN_JWT_SECRET")
ADMIN_BOOTSTRAP_EMAIL = os.getenv("ADMIN_BOOTSTRAP_EMAIL")
ADMIN_BOOTSTRAP_PASSWORD_HASH = os.getenv("ADMIN_BOOTSTRAP_PASSWORD_HASH")
PPT_SUBMISSION_DEADLINE = os.getenv("PPT_SUBMISSION_DEADLINE")
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME", "f5lz9bul")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY", "713148592682745")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")
CLOUDINARY_UPLOAD_PRESET = os.getenv("CLOUDINARY_UPLOAD_PRESET", "Nmiet-sih-ppt")
SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
SMTP_FROM = os.getenv("SMTP_FROM", "NMIET SIH Portal <no-reply@nmiet.edu.in>")
PORTAL_URL = os.getenv("PORTAL_URL", "https://nmietsihportal.vercel.app")
