/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as OrganizingCommitteeRouteImport } from './routes/organizing-committee'
import { Route as PptSubmissionRouteImport } from './routes/ppt-submission'
import { Route as PptTemplateRouteImport } from './routes/ppt-template'
import { Route as PreviousYearsRouteImport } from './routes/previous-years'
import { Route as ProblemStatementsRouteImport } from './routes/problem-statements'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SubmissionGuidelinesRouteImport } from './routes/submission-guidelines'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEmailRouteImport } from './routes/admin/email'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPptRouteImport } from './routes/admin/ppt'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiProblemStatementsRouteImport } from './routes/api/problem-statements'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiThemesRouteImport } from './routes/api/themes'
import { Route as JudgeEvaluationRouteImport } from './routes/judge/evaluation'
import { Route as JudgeLoginRouteImport } from './routes/judge/login'
import { Route as TrackLoginRouteImport } from './routes/track/login'
import { Route as TrackQueueRouteImport } from './routes/track/queue'
import { Route as AdminEvaluationIndexRouteImport } from './routes/admin/evaluation/index'
import { Route as AdminEvaluationCoordinatorsRouteImport } from './routes/admin/evaluation/coordinators'
import { Route as AdminEvaluationCriteriaRouteImport } from './routes/admin/evaluation/criteria'
import { Route as AdminEvaluationJudgesRouteImport } from './routes/admin/evaluation/judges'
import { Route as AdminEvaluationTracksRouteImport } from './routes/admin/evaluation/tracks'
import { Route as AdminPptIdRouteImport } from './routes/admin/ppt/$id'
import { Route as AdminRegistrationsIdRouteImport } from './routes/admin/registrations/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizingCommitteeRoute = OrganizingCommitteeRouteImport.update({
  id: '/organizing-committee',
  path: '/organizing-committee',
  getParentRoute: () => rootRouteImport,
} as any)
const PptSubmissionRoute = PptSubmissionRouteImport.update({
  id: '/ppt-submission',
  path: '/ppt-submission',
  getParentRoute: () => rootRouteImport,
} as any)
const PptTemplateRoute = PptTemplateRouteImport.update({
  id: '/ppt-template',
  path: '/ppt-template',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviousYearsRoute = PreviousYearsRouteImport.update({
  id: '/previous-years',
  path: '/previous-years',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemStatementsRoute = ProblemStatementsRouteImport.update({
  id: '/problem-statements',
  path: '/problem-statements',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionGuidelinesRoute = SubmissionGuidelinesRouteImport.update({
  id: '/submission-guidelines',
  path: '/submission-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/admin/email',
  path: '/admin/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPptRoute = AdminPptRouteImport.update({
  id: '/admin/ppt',
  path: '/admin/ppt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/admin/registrations',
  path: '/admin/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProblemStatementsRoute = ApiProblemStatementsRouteImport.update({
  id: '/api/problem-statements',
  path: '/api/problem-statements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemesRoute = ApiThemesRouteImport.update({
  id: '/api/themes',
  path: '/api/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeEvaluationRoute = JudgeEvaluationRouteImport.update({
  id: '/judge/evaluation',
  path: '/judge/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeLoginRoute = JudgeLoginRouteImport.update({
  id: '/judge/login',
  path: '/judge/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackLoginRoute = TrackLoginRouteImport.update({
  id: '/track/login',
  path: '/track/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackQueueRoute = TrackQueueRouteImport.update({
  id: '/track/queue',
  path: '/track/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluationIndexRoute = AdminEvaluationIndexRouteImport.update({
  id: '/admin/evaluation/',
  path: '/admin/evaluation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluationCoordinatorsRoute =
  AdminEvaluationCoordinatorsRouteImport.update({
    id: '/admin/evaluation/coordinators',
    path: '/admin/evaluation/coordinators',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEvaluationCriteriaRoute = AdminEvaluationCriteriaRouteImport.update({
  id: '/admin/evaluation/criteria',
  path: '/admin/evaluation/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluationJudgesRoute = AdminEvaluationJudgesRouteImport.update({
  id: '/admin/evaluation/judges',
  path: '/admin/evaluation/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEvaluationTracksRoute = AdminEvaluationTracksRouteImport.update({
  id: '/admin/evaluation/tracks',
  path: '/admin/evaluation/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPptIdRoute = AdminPptIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPptRoute,
} as any)
const AdminRegistrationsIdRoute = AdminRegistrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRegistrationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/organizing-committee': typeof OrganizingCommitteeRoute
  '/ppt-submission': typeof PptSubmissionRoute
  '/ppt-template': typeof PptTemplateRoute
  '/previous-years': typeof PreviousYearsRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/themes': typeof ThemesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ppt': typeof AdminPptRouteWithChildren
  '/admin/registrations': typeof AdminRegistrationsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/problem-statements': typeof ApiProblemStatementsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/themes': typeof ApiThemesRoute
  '/judge/evaluation': typeof JudgeEvaluationRoute
  '/judge/login': typeof JudgeLoginRoute
  '/track/login': typeof TrackLoginRoute
  '/track/queue': typeof TrackQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/evaluation/coordinators': typeof AdminEvaluationCoordinatorsRoute
  '/admin/evaluation/criteria': typeof AdminEvaluationCriteriaRoute
  '/admin/evaluation/judges': typeof AdminEvaluationJudgesRoute
  '/admin/evaluation/tracks': typeof AdminEvaluationTracksRoute
  '/admin/ppt/$id': typeof AdminPptIdRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/evaluation/': typeof AdminEvaluationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/organizing-committee': typeof OrganizingCommitteeRoute
  '/ppt-submission': typeof PptSubmissionRoute
  '/ppt-template': typeof PptTemplateRoute
  '/previous-years': typeof PreviousYearsRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/themes': typeof ThemesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ppt': typeof AdminPptRouteWithChildren
  '/admin/registrations': typeof AdminRegistrationsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/problem-statements': typeof ApiProblemStatementsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/themes': typeof ApiThemesRoute
  '/judge/evaluation': typeof JudgeEvaluationRoute
  '/judge/login': typeof JudgeLoginRoute
  '/track/login': typeof TrackLoginRoute
  '/track/queue': typeof TrackQueueRoute
  '/admin': typeof AdminIndexRoute
  '/admin/evaluation/coordinators': typeof AdminEvaluationCoordinatorsRoute
  '/admin/evaluation/criteria': typeof AdminEvaluationCriteriaRoute
  '/admin/evaluation/judges': typeof AdminEvaluationJudgesRoute
  '/admin/evaluation/tracks': typeof AdminEvaluationTracksRoute
  '/admin/ppt/$id': typeof AdminPptIdRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/evaluation': typeof AdminEvaluationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guidelines': typeof GuidelinesRoute
  '/organizing-committee': typeof OrganizingCommitteeRoute
  '/ppt-submission': typeof PptSubmissionRoute
  '/ppt-template': typeof PptTemplateRoute
  '/previous-years': typeof PreviousYearsRoute
  '/problem-statements': typeof ProblemStatementsRoute
  '/register': typeof RegisterRoute
  '/submission-guidelines': typeof SubmissionGuidelinesRoute
  '/themes': typeof ThemesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/ppt': typeof AdminPptRouteWithChildren
  '/admin/registrations': typeof AdminRegistrationsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/api/problem-statements': typeof ApiProblemStatementsRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/themes': typeof ApiThemesRoute
  '/judge/evaluation': typeof JudgeEvaluationRoute
  '/judge/login': typeof JudgeLoginRoute
  '/track/login': typeof TrackLoginRoute
  '/track/queue': typeof TrackQueueRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/evaluation/coordinators': typeof AdminEvaluationCoordinatorsRoute
  '/admin/evaluation/criteria': typeof AdminEvaluationCriteriaRoute
  '/admin/evaluation/judges': typeof AdminEvaluationJudgesRoute
  '/admin/evaluation/tracks': typeof AdminEvaluationTracksRoute
  '/admin/ppt/$id': typeof AdminPptIdRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/evaluation/': typeof AdminEvaluationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guidelines'
    | '/organizing-committee'
    | '/ppt-submission'
    | '/ppt-template'
    | '/previous-years'
    | '/problem-statements'
    | '/register'
    | '/submission-guidelines'
    | '/themes'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/email'
    | '/admin/login'
    | '/admin/ppt'
    | '/admin/registrations'
    | '/admin/users'
    | '/api/problem-statements'
    | '/api/register'
    | '/api/themes'
    | '/judge/evaluation'
    | '/judge/login'
    | '/track/login'
    | '/track/queue'
    | '/admin/'
    | '/admin/evaluation/coordinators'
    | '/admin/evaluation/criteria'
    | '/admin/evaluation/judges'
    | '/admin/evaluation/tracks'
    | '/admin/ppt/$id'
    | '/admin/registrations/$id'
    | '/admin/evaluation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guidelines'
    | '/organizing-committee'
    | '/ppt-submission'
    | '/ppt-template'
    | '/previous-years'
    | '/problem-statements'
    | '/register'
    | '/submission-guidelines'
    | '/themes'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/email'
    | '/admin/login'
    | '/admin/ppt'
    | '/admin/registrations'
    | '/admin/users'
    | '/api/problem-statements'
    | '/api/register'
    | '/api/themes'
    | '/judge/evaluation'
    | '/judge/login'
    | '/track/login'
    | '/track/queue'
    | '/admin'
    | '/admin/evaluation/coordinators'
    | '/admin/evaluation/criteria'
    | '/admin/evaluation/judges'
    | '/admin/evaluation/tracks'
    | '/admin/ppt/$id'
    | '/admin/registrations/$id'
    | '/admin/evaluation'
  id:
    | '__root__'
    | '/'
    | '/guidelines'
    | '/organizing-committee'
    | '/ppt-submission'
    | '/ppt-template'
    | '/previous-years'
    | '/problem-statements'
    | '/register'
    | '/submission-guidelines'
    | '/themes'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/email'
    | '/admin/login'
    | '/admin/ppt'
    | '/admin/registrations'
    | '/admin/users'
    | '/api/problem-statements'
    | '/api/register'
    | '/api/themes'
    | '/judge/evaluation'
    | '/judge/login'
    | '/track/login'
    | '/track/queue'
    | '/admin/'
    | '/admin/evaluation/coordinators'
    | '/admin/evaluation/criteria'
    | '/admin/evaluation/judges'
    | '/admin/evaluation/tracks'
    | '/admin/ppt/$id'
    | '/admin/registrations/$id'
    | '/admin/evaluation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidelinesRoute: typeof GuidelinesRoute
  OrganizingCommitteeRoute: typeof OrganizingCommitteeRoute
  PptSubmissionRoute: typeof PptSubmissionRoute
  PptTemplateRoute: typeof PptTemplateRoute
  PreviousYearsRoute: typeof PreviousYearsRoute
  ProblemStatementsRoute: typeof ProblemStatementsRoute
  RegisterRoute: typeof RegisterRoute
  SubmissionGuidelinesRoute: typeof SubmissionGuidelinesRoute
  ThemesRoute: typeof ThemesRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmailRoute: typeof AdminEmailRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPptRoute: typeof AdminPptRouteWithChildren
  AdminRegistrationsRoute: typeof AdminRegistrationsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  ApiProblemStatementsRoute: typeof ApiProblemStatementsRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiThemesRoute: typeof ApiThemesRoute
  JudgeEvaluationRoute: typeof JudgeEvaluationRoute
  JudgeLoginRoute: typeof JudgeLoginRoute
  TrackLoginRoute: typeof TrackLoginRoute
  TrackQueueRoute: typeof TrackQueueRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEvaluationCoordinatorsRoute: typeof AdminEvaluationCoordinatorsRoute
  AdminEvaluationCriteriaRoute: typeof AdminEvaluationCriteriaRoute
  AdminEvaluationJudgesRoute: typeof AdminEvaluationJudgesRoute
  AdminEvaluationTracksRoute: typeof AdminEvaluationTracksRoute
  AdminEvaluationIndexRoute: typeof AdminEvaluationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizing-committee': {
      id: '/organizing-committee'
      path: '/organizing-committee'
      fullPath: '/organizing-committee'
      preLoaderRoute: typeof OrganizingCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppt-submission': {
      id: '/ppt-submission'
      path: '/ppt-submission'
      fullPath: '/ppt-submission'
      preLoaderRoute: typeof PptSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppt-template': {
      id: '/ppt-template'
      path: '/ppt-template'
      fullPath: '/ppt-template'
      preLoaderRoute: typeof PptTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previous-years': {
      id: '/previous-years'
      path: '/previous-years'
      fullPath: '/previous-years'
      preLoaderRoute: typeof PreviousYearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-statements': {
      id: '/problem-statements'
      path: '/problem-statements'
      fullPath: '/problem-statements'
      preLoaderRoute: typeof ProblemStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission-guidelines': {
      id: '/submission-guidelines'
      path: '/submission-guidelines'
      fullPath: '/submission-guidelines'
      preLoaderRoute: typeof SubmissionGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/admin/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ppt': {
      id: '/admin/ppt'
      path: '/admin/ppt'
      fullPath: '/admin/ppt'
      preLoaderRoute: typeof AdminPptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/admin/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/problem-statements': {
      id: '/api/problem-statements'
      path: '/api/problem-statements'
      fullPath: '/api/problem-statements'
      preLoaderRoute: typeof ApiProblemStatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/themes': {
      id: '/api/themes'
      path: '/api/themes'
      fullPath: '/api/themes'
      preLoaderRoute: typeof ApiThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/evaluation': {
      id: '/judge/evaluation'
      path: '/judge/evaluation'
      fullPath: '/judge/evaluation'
      preLoaderRoute: typeof JudgeEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/login': {
      id: '/judge/login'
      path: '/judge/login'
      fullPath: '/judge/login'
      preLoaderRoute: typeof JudgeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/login': {
      id: '/track/login'
      path: '/track/login'
      fullPath: '/track/login'
      preLoaderRoute: typeof TrackLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/queue': {
      id: '/track/queue'
      path: '/track/queue'
      fullPath: '/track/queue'
      preLoaderRoute: typeof TrackQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluation/': {
      id: '/admin/evaluation/'
      path: '/admin/evaluation'
      fullPath: '/admin/evaluation/'
      preLoaderRoute: typeof AdminEvaluationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluation/coordinators': {
      id: '/admin/evaluation/coordinators'
      path: '/admin/evaluation/coordinators'
      fullPath: '/admin/evaluation/coordinators'
      preLoaderRoute: typeof AdminEvaluationCoordinatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluation/criteria': {
      id: '/admin/evaluation/criteria'
      path: '/admin/evaluation/criteria'
      fullPath: '/admin/evaluation/criteria'
      preLoaderRoute: typeof AdminEvaluationCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluation/judges': {
      id: '/admin/evaluation/judges'
      path: '/admin/evaluation/judges'
      fullPath: '/admin/evaluation/judges'
      preLoaderRoute: typeof AdminEvaluationJudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/evaluation/tracks': {
      id: '/admin/evaluation/tracks'
      path: '/admin/evaluation/tracks'
      fullPath: '/admin/evaluation/tracks'
      preLoaderRoute: typeof AdminEvaluationTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ppt/$id': {
      id: '/admin/ppt/$id'
      path: '/$id'
      fullPath: '/admin/ppt/$id'
      preLoaderRoute: typeof AdminPptIdRouteImport
      parentRoute: typeof AdminPptRoute
    }
    '/admin/registrations/$id': {
      id: '/admin/registrations/$id'
      path: '/$id'
      fullPath: '/admin/registrations/$id'
      preLoaderRoute: typeof AdminRegistrationsIdRouteImport
      parentRoute: typeof AdminRegistrationsRoute
    }
  }
}

interface AdminPptRouteChildren {
  AdminPptIdRoute: typeof AdminPptIdRoute
}

const AdminPptRouteChildren: AdminPptRouteChildren = {
  AdminPptIdRoute: AdminPptIdRoute,
}

const AdminPptRouteWithChildren = AdminPptRoute._addFileChildren(
  AdminPptRouteChildren,
)

interface AdminRegistrationsRouteChildren {
  AdminRegistrationsIdRoute: typeof AdminRegistrationsIdRoute
}

const AdminRegistrationsRouteChildren: AdminRegistrationsRouteChildren = {
  AdminRegistrationsIdRoute: AdminRegistrationsIdRoute,
}

const AdminRegistrationsRouteWithChildren =
  AdminRegistrationsRoute._addFileChildren(AdminRegistrationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidelinesRoute: GuidelinesRoute,
  OrganizingCommitteeRoute: OrganizingCommitteeRoute,
  PptSubmissionRoute: PptSubmissionRoute,
  PptTemplateRoute: PptTemplateRoute,
  PreviousYearsRoute: PreviousYearsRoute,
  ProblemStatementsRoute: ProblemStatementsRoute,
  RegisterRoute: RegisterRoute,
  SubmissionGuidelinesRoute: SubmissionGuidelinesRoute,
  ThemesRoute: ThemesRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmailRoute: AdminEmailRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPptRoute: AdminPptRouteWithChildren,
  AdminRegistrationsRoute: AdminRegistrationsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  ApiProblemStatementsRoute: ApiProblemStatementsRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiThemesRoute: ApiThemesRoute,
  JudgeEvaluationRoute: JudgeEvaluationRoute,
  JudgeLoginRoute: JudgeLoginRoute,
  TrackLoginRoute: TrackLoginRoute,
  TrackQueueRoute: TrackQueueRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEvaluationCoordinatorsRoute: AdminEvaluationCoordinatorsRoute,
  AdminEvaluationCriteriaRoute: AdminEvaluationCriteriaRoute,
  AdminEvaluationJudgesRoute: AdminEvaluationJudgesRoute,
  AdminEvaluationTracksRoute: AdminEvaluationTracksRoute,
  AdminEvaluationIndexRoute: AdminEvaluationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
